export interface AIQuestion {
  id: string;
  title: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  points: number;
  problemStatement: string;
  sampleInput: string;
  sampleOutput: string;
  constraints: string[];
  tableSchema: {
    tableName: string;
    columns: { name: string; type: string }[];
  };
  hints: string[];
  initialCode: string;
  solutionCode: string;
  language?: string;
}

export const AI_QUESTION_POOL: AIQuestion[] = [
  // ==========================================
  // EASY QUESTIONS
  // ==========================================
  {
    id: "ai-easy-01",
    title: "Create a PyTorch Tensor",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `create_tensor(data)` that converts a Python list into a PyTorch float32 tensor.",
    sampleInput: "data = [[1, 2], [3, 4]]",
    sampleOutput: "tensor([[1., 2.], [3., 4.]])",
    constraints: ["Use torch.tensor with dtype=torch.float32."],
    tableSchema: { tableName: "create_tensor(data)", columns: [{ name: "data", type: "list" }, { name: "Returns", type: "torch.Tensor" }] },
    hints: ["torch.tensor(data, dtype=torch.float32)"],
    initialCode: "import torch\n\ndef create_tensor(data):\n    pass",
    solutionCode: "import torch\n\ndef create_tensor(data):\n    return torch.tensor(data, dtype=torch.float32)",
  },
  {
    id: "ai-easy-02",
    title: "ReLU Activation Function",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `apply_relu(x)` that applies the ReLU activation function to a PyTorch tensor manually (without using nn.ReLU). ReLU(x) = max(0, x).",
    sampleInput: "x = tensor([-2, -1, 0, 1, 2])",
    sampleOutput: "tensor([0, 0, 0, 1, 2])",
    constraints: ["Do NOT use torch.nn.ReLU.", "Use torch.clamp or torch.maximum."],
    tableSchema: { tableName: "apply_relu(x)", columns: [{ name: "x", type: "torch.Tensor" }, { name: "Returns", type: "torch.Tensor" }] },
    hints: ["torch.clamp(x, min=0) or torch.maximum(x, torch.zeros_like(x))"],
    initialCode: "import torch\n\ndef apply_relu(x):\n    pass",
    solutionCode: "import torch\n\ndef apply_relu(x):\n    return torch.clamp(x, min=0)",
  },
  {
    id: "ai-easy-03",
    title: "Softmax Function",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `softmax(logits)` that computes the softmax of a 1D tensor of logits. Use the numerically stable version by subtracting the max value first.",
    sampleInput: "logits = tensor([2.0, 1.0, 0.1])",
    sampleOutput: "tensor([0.6590, 0.2424, 0.0986])",
    constraints: ["Subtract max(logits) for numerical stability."],
    tableSchema: { tableName: "softmax(logits)", columns: [{ name: "logits", type: "torch.Tensor" }, { name: "Returns", type: "torch.Tensor" }] },
    hints: ["exp_x = torch.exp(logits - logits.max()); exp_x / exp_x.sum()"],
    initialCode: "import torch\n\ndef softmax(logits):\n    pass",
    solutionCode: "import torch\n\ndef softmax(logits):\n    exp_x = torch.exp(logits - logits.max())\n    return exp_x / exp_x.sum()",
  },
  {
    id: "ai-easy-04",
    title: "One-Hot Encoding with PyTorch",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `one_hot(labels, num_classes)` that converts a 1D tensor of integer labels into a one-hot encoded 2D tensor.",
    sampleInput: "labels = tensor([0, 2, 1]), num_classes = 3",
    sampleOutput: "tensor([[1,0,0],[0,0,1],[0,1,0]])",
    constraints: ["Use torch.nn.functional.one_hot or manual indexing."],
    tableSchema: { tableName: "one_hot(labels, num_classes)", columns: [{ name: "labels", type: "torch.Tensor" }, { name: "num_classes", type: "int" }, { name: "Returns", type: "torch.Tensor" }] },
    hints: ["torch.nn.functional.one_hot(labels, num_classes)"],
    initialCode: "import torch\nimport torch.nn.functional as F\n\ndef one_hot(labels, num_classes):\n    pass",
    solutionCode: "import torch\nimport torch.nn.functional as F\n\ndef one_hot(labels, num_classes):\n    return F.one_hot(labels, num_classes)",
  },
  {
    id: "ai-easy-05",
    title: "Cross-Entropy Loss",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `compute_ce_loss(logits, targets)` that computes the cross-entropy loss for classification using PyTorch's CrossEntropyLoss.",
    sampleInput: "logits (batch_size, num_classes), targets (batch_size,)",
    sampleOutput: "Scalar loss value",
    constraints: ["Use nn.CrossEntropyLoss. Logits are raw (unnormalized)."],
    tableSchema: { tableName: "compute_ce_loss(logits, targets)", columns: [{ name: "logits", type: "torch.Tensor" }, { name: "targets", type: "torch.Tensor" }, { name: "Returns", type: "torch.Tensor (scalar)" }] },
    hints: ["nn.CrossEntropyLoss()(logits, targets)"],
    initialCode: "import torch\nimport torch.nn as nn\n\ndef compute_ce_loss(logits, targets):\n    pass",
    solutionCode: "import torch\nimport torch.nn as nn\n\ndef compute_ce_loss(logits, targets):\n    criterion = nn.CrossEntropyLoss()\n    return criterion(logits, targets)",
  },
  {
    id: "ai-easy-06",
    title: "Simple Linear Layer",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `create_linear(in_features, out_features)` that creates and returns a PyTorch nn.Linear layer.",
    sampleInput: "in_features=10, out_features=5",
    sampleOutput: "nn.Linear(10, 5)",
    constraints: ["Use torch.nn.Linear."],
    tableSchema: { tableName: "create_linear(in_features, out_features)", columns: [{ name: "in_features", type: "int" }, { name: "out_features", type: "int" }, { name: "Returns", type: "nn.Linear" }] },
    hints: ["nn.Linear(in_features, out_features)"],
    initialCode: "import torch.nn as nn\n\ndef create_linear(in_features, out_features):\n    pass",
    solutionCode: "import torch.nn as nn\n\ndef create_linear(in_features, out_features):\n    return nn.Linear(in_features, out_features)",
  },
  {
    id: "ai-easy-07",
    title: "Gradient Computation with Autograd",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `compute_gradient(x_val)` that creates a tensor x with requires_grad=True, computes y = x^2 + 3x + 1, calls backward(), and returns x.grad as a float.",
    sampleInput: "x_val = 2.0",
    sampleOutput: "7.0 (dy/dx = 2x + 3 at x=2)",
    constraints: ["Use requires_grad=True and .backward()."],
    tableSchema: { tableName: "compute_gradient(x_val)", columns: [{ name: "x_val", type: "float" }, { name: "Returns", type: "float" }] },
    hints: ["x = torch.tensor(x_val, requires_grad=True); y = x**2 + 3*x + 1; y.backward(); x.grad.item()"],
    initialCode: "import torch\n\ndef compute_gradient(x_val):\n    pass",
    solutionCode: "import torch\n\ndef compute_gradient(x_val):\n    x = torch.tensor(x_val, requires_grad=True)\n    y = x**2 + 3*x + 1\n    y.backward()\n    return x.grad.item()",
  },

  // ==========================================
  // MEDIUM QUESTIONS
  // ==========================================
  {
    id: "ai-med-01",
    title: "Two-Layer Neural Network Module",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a PyTorch nn.Module class `TwoLayerNet` with: Linear(input_dim, hidden_dim) → ReLU → Linear(hidden_dim, output_dim). Implement __init__ and forward.",
    sampleInput: "input_dim=784, hidden_dim=128, output_dim=10",
    sampleOutput: "Output tensor of shape (batch, 10)",
    constraints: ["Use nn.ReLU between layers.", "No dropout or batch norm required."],
    tableSchema: { tableName: "TwoLayerNet", columns: [{ name: "__init__(input_dim, hidden_dim, output_dim)", type: "constructor" }, { name: "forward(x)", type: "torch.Tensor" }] },
    hints: ["self.fc1 = nn.Linear(...); self.relu = nn.ReLU(); self.fc2 = nn.Linear(...)"],
    initialCode: "import torch\nimport torch.nn as nn\n\nclass TwoLayerNet(nn.Module):\n    def __init__(self, input_dim, hidden_dim, output_dim):\n        super().__init__()\n        pass\n    \n    def forward(self, x):\n        pass",
    solutionCode: "import torch\nimport torch.nn as nn\n\nclass TwoLayerNet(nn.Module):\n    def __init__(self, input_dim, hidden_dim, output_dim):\n        super().__init__()\n        self.fc1 = nn.Linear(input_dim, hidden_dim)\n        self.relu = nn.ReLU()\n        self.fc2 = nn.Linear(hidden_dim, output_dim)\n    \n    def forward(self, x):\n        return self.fc2(self.relu(self.fc1(x)))",
  },
  {
    id: "ai-med-02",
    title: "Training Loop Step",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a function `train_step(model, optimizer, criterion, X_batch, y_batch)` that performs one training step: forward pass, loss computation, backward pass, and optimizer step. Return the loss value.",
    sampleInput: "model, optimizer, criterion, input batch, target batch",
    sampleOutput: "loss.item() float",
    constraints: ["Remember to zero gradients before backward.", "Return loss.item()."],
    tableSchema: { tableName: "train_step(...)", columns: [{ name: "model", type: "nn.Module" }, { name: "optimizer", type: "Optimizer" }, { name: "Returns", type: "float" }] },
    hints: ["optimizer.zero_grad(); output = model(X_batch); loss = criterion(output, y_batch); loss.backward(); optimizer.step()"],
    initialCode: "def train_step(model, optimizer, criterion, X_batch, y_batch):\n    pass",
    solutionCode: "def train_step(model, optimizer, criterion, X_batch, y_batch):\n    optimizer.zero_grad()\n    output = model(X_batch)\n    loss = criterion(output, y_batch)\n    loss.backward()\n    optimizer.step()\n    return loss.item()",
  },
  {
    id: "ai-med-03",
    title: "Scaled Dot-Product Attention",
    difficulty: "MEDIUM",
    points: 35,
    problemStatement: "Implement the scaled dot-product attention: Attention(Q, K, V) = softmax(Q·K^T / √d_k) · V. Write a function `scaled_attention(Q, K, V)` using PyTorch.",
    sampleInput: "Q, K, V tensors of shape (batch, seq_len, d_k)",
    sampleOutput: "Output tensor of shape (batch, seq_len, d_k)",
    constraints: ["Divide by sqrt(d_k) before softmax.", "Use torch.matmul."],
    tableSchema: { tableName: "scaled_attention(Q, K, V)", columns: [{ name: "Q, K, V", type: "torch.Tensor" }, { name: "Returns", type: "torch.Tensor" }] },
    hints: ["scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(d_k)"],
    initialCode: "import torch\nimport math\n\ndef scaled_attention(Q, K, V):\n    pass",
    solutionCode: "import torch\nimport math\n\ndef scaled_attention(Q, K, V):\n    d_k = Q.size(-1)\n    scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(d_k)\n    weights = torch.softmax(scores, dim=-1)\n    return torch.matmul(weights, V)",
  },
  {
    id: "ai-med-04",
    title: "CNN Feature Extractor",
    difficulty: "MEDIUM",
    points: 35,
    problemStatement: "Write a PyTorch nn.Module class `SimpleCNN` with: Conv2d(1, 32, 3, padding=1) → ReLU → MaxPool2d(2) → Conv2d(32, 64, 3, padding=1) → ReLU → MaxPool2d(2). Implement forward for a 28x28 input.",
    sampleInput: "Input tensor of shape (batch, 1, 28, 28)",
    sampleOutput: "Feature tensor of shape (batch, 64, 7, 7)",
    constraints: ["Use nn.Conv2d, nn.ReLU, nn.MaxPool2d."],
    tableSchema: { tableName: "SimpleCNN", columns: [{ name: "forward(x)", type: "torch.Tensor → (batch, 64, 7, 7)" }] },
    hints: ["Two conv-relu-pool blocks, input channels: 1→32→64"],
    initialCode: "import torch\nimport torch.nn as nn\n\nclass SimpleCNN(nn.Module):\n    def __init__(self):\n        super().__init__()\n        pass\n    \n    def forward(self, x):\n        pass",
    solutionCode: "import torch\nimport torch.nn as nn\n\nclass SimpleCNN(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.conv1 = nn.Conv2d(1, 32, 3, padding=1)\n        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)\n        self.relu = nn.ReLU()\n        self.pool = nn.MaxPool2d(2)\n    \n    def forward(self, x):\n        x = self.pool(self.relu(self.conv1(x)))\n        x = self.pool(self.relu(self.conv2(x)))\n        return x",
  },
  {
    id: "ai-med-05",
    title: "Positional Encoding",
    difficulty: "MEDIUM",
    points: 35,
    problemStatement: "Write a function `positional_encoding(seq_len, d_model)` that generates the sinusoidal positional encoding matrix of shape (seq_len, d_model) as described in 'Attention Is All You Need'.",
    sampleInput: "seq_len=50, d_model=512",
    sampleOutput: "Tensor of shape (50, 512) with sin/cos patterns",
    constraints: ["Even indices: sin(pos / 10000^(2i/d_model)), Odd indices: cos(pos / 10000^(2i/d_model))"],
    tableSchema: { tableName: "positional_encoding(seq_len, d_model)", columns: [{ name: "seq_len", type: "int" }, { name: "d_model", type: "int" }, { name: "Returns", type: "torch.Tensor" }] },
    hints: ["position = torch.arange(seq_len).unsqueeze(1); div_term = torch.exp(...)"],
    initialCode: "import torch\nimport math\n\ndef positional_encoding(seq_len, d_model):\n    pass",
    solutionCode: "import torch\nimport math\n\ndef positional_encoding(seq_len, d_model):\n    pe = torch.zeros(seq_len, d_model)\n    position = torch.arange(0, seq_len, dtype=torch.float).unsqueeze(1)\n    div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))\n    pe[:, 0::2] = torch.sin(position * div_term)\n    pe[:, 1::2] = torch.cos(position * div_term)\n    return pe",
  },
  {
    id: "ai-med-06",
    title: "Word Embedding Layer",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a function `create_embedding(vocab_size, embed_dim)` that creates an nn.Embedding layer and a function that looks up embeddings for a batch of token IDs.",
    sampleInput: "vocab_size=10000, embed_dim=256",
    sampleOutput: "Embedding layer + lookup function",
    constraints: ["Use nn.Embedding."],
    tableSchema: { tableName: "create_embedding(vocab_size, embed_dim)", columns: [{ name: "vocab_size", type: "int" }, { name: "embed_dim", type: "int" }, { name: "Returns", type: "nn.Embedding" }] },
    hints: ["nn.Embedding(vocab_size, embed_dim)"],
    initialCode: "import torch.nn as nn\n\ndef create_embedding(vocab_size, embed_dim):\n    pass",
    solutionCode: "import torch.nn as nn\n\ndef create_embedding(vocab_size, embed_dim):\n    return nn.Embedding(vocab_size, embed_dim)",
  },
  {
    id: "ai-med-07",
    title: "Batch Normalization Effect",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a PyTorch nn.Module class `NormNet` that applies: Linear(in, 128) → BatchNorm1d(128) → ReLU → Linear(128, out). Implement both __init__ and forward.",
    sampleInput: "in_features=50, out_features=10",
    sampleOutput: "Output tensor (batch, 10)",
    constraints: ["Use nn.BatchNorm1d between the first linear and ReLU."],
    tableSchema: { tableName: "NormNet", columns: [{ name: "__init__(in_f, out_f)", type: "constructor" }, { name: "forward(x)", type: "torch.Tensor" }] },
    hints: ["self.bn = nn.BatchNorm1d(128)"],
    initialCode: "import torch.nn as nn\n\nclass NormNet(nn.Module):\n    def __init__(self, in_features, out_features):\n        super().__init__()\n        pass\n    \n    def forward(self, x):\n        pass",
    solutionCode: "import torch.nn as nn\n\nclass NormNet(nn.Module):\n    def __init__(self, in_features, out_features):\n        super().__init__()\n        self.fc1 = nn.Linear(in_features, 128)\n        self.bn = nn.BatchNorm1d(128)\n        self.relu = nn.ReLU()\n        self.fc2 = nn.Linear(128, out_features)\n    \n    def forward(self, x):\n        return self.fc2(self.relu(self.bn(self.fc1(x))))",
  },

  // ==========================================
  // HARD QUESTIONS
  // ==========================================
  {
    id: "ai-hard-01",
    title: "Multi-Head Attention Module",
    difficulty: "HARD",
    points: 50,
    problemStatement: "Write a PyTorch nn.Module class `MultiHeadAttention` that implements multi-head attention with num_heads splitting. Project Q, K, V, split into heads, apply scaled dot-product attention, concatenate, and project output.",
    sampleInput: "d_model=512, num_heads=8, input (batch, seq_len, 512)",
    sampleOutput: "Output tensor (batch, seq_len, 512)",
    constraints: ["d_model must be divisible by num_heads.", "Use separate linear projections for Q, K, V, and output."],
    tableSchema: { tableName: "MultiHeadAttention", columns: [{ name: "__init__(d_model, num_heads)", type: "constructor" }, { name: "forward(Q, K, V)", type: "torch.Tensor" }] },
    hints: ["d_k = d_model // num_heads; reshape to (batch, heads, seq, d_k)"],
    initialCode: "import torch\nimport torch.nn as nn\nimport math\n\nclass MultiHeadAttention(nn.Module):\n    def __init__(self, d_model, num_heads):\n        super().__init__()\n        pass\n    \n    def forward(self, Q, K, V):\n        pass",
    solutionCode: "import torch\nimport torch.nn as nn\nimport math\n\nclass MultiHeadAttention(nn.Module):\n    def __init__(self, d_model, num_heads):\n        super().__init__()\n        self.d_model = d_model\n        self.num_heads = num_heads\n        self.d_k = d_model // num_heads\n        self.W_q = nn.Linear(d_model, d_model)\n        self.W_k = nn.Linear(d_model, d_model)\n        self.W_v = nn.Linear(d_model, d_model)\n        self.W_o = nn.Linear(d_model, d_model)\n    \n    def forward(self, Q, K, V):\n        batch = Q.size(0)\n        Q = self.W_q(Q).view(batch, -1, self.num_heads, self.d_k).transpose(1, 2)\n        K = self.W_k(K).view(batch, -1, self.num_heads, self.d_k).transpose(1, 2)\n        V = self.W_v(V).view(batch, -1, self.num_heads, self.d_k).transpose(1, 2)\n        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_k)\n        attn = torch.softmax(scores, dim=-1)\n        out = torch.matmul(attn, V)\n        out = out.transpose(1, 2).contiguous().view(batch, -1, self.d_model)\n        return self.W_o(out)",
  },
  {
    id: "ai-hard-02",
    title: "GAN Generator Network",
    difficulty: "HARD",
    points: 50,
    problemStatement: "Write a PyTorch nn.Module class `Generator` for a simple GAN that maps a latent vector z (latent_dim) to a 784-dimensional output (28x28 flattened) using: Linear → BatchNorm → ReLU → Linear → BatchNorm → ReLU → Linear → Tanh.",
    sampleInput: "latent_dim=100",
    sampleOutput: "Tensor of shape (batch, 784) with values in [-1, 1]",
    constraints: ["Output activation must be Tanh.", "Use BatchNorm1d between layers."],
    tableSchema: { tableName: "Generator", columns: [{ name: "__init__(latent_dim)", type: "constructor" }, { name: "forward(z)", type: "torch.Tensor (batch, 784)" }] },
    hints: ["Linear(100, 256) → BN → ReLU → Linear(256, 512) → BN → ReLU → Linear(512, 784) → Tanh"],
    initialCode: "import torch.nn as nn\n\nclass Generator(nn.Module):\n    def __init__(self, latent_dim):\n        super().__init__()\n        pass\n    \n    def forward(self, z):\n        pass",
    solutionCode: "import torch.nn as nn\n\nclass Generator(nn.Module):\n    def __init__(self, latent_dim):\n        super().__init__()\n        self.net = nn.Sequential(\n            nn.Linear(latent_dim, 256),\n            nn.BatchNorm1d(256),\n            nn.ReLU(),\n            nn.Linear(256, 512),\n            nn.BatchNorm1d(512),\n            nn.ReLU(),\n            nn.Linear(512, 784),\n            nn.Tanh()\n        )\n    \n    def forward(self, z):\n        return self.net(z)",
  },
  {
    id: "ai-hard-03",
    title: "LSTM Sequence Classifier",
    difficulty: "HARD",
    points: 45,
    problemStatement: "Write a PyTorch nn.Module class `LSTMClassifier` with: Embedding(vocab_size, embed_dim) → LSTM(embed_dim, hidden_dim, batch_first=True) → Linear(hidden_dim, num_classes). Use the last hidden state for classification.",
    sampleInput: "vocab_size=5000, embed_dim=128, hidden_dim=256, num_classes=2",
    sampleOutput: "Output logits of shape (batch, 2)",
    constraints: ["Use batch_first=True.", "Extract last hidden state from LSTM output."],
    tableSchema: { tableName: "LSTMClassifier", columns: [{ name: "__init__(...)", type: "constructor" }, { name: "forward(x)", type: "torch.Tensor (batch, num_classes)" }] },
    hints: ["out, (hn, cn) = self.lstm(embedded); use hn[-1] for classification"],
    initialCode: "import torch\nimport torch.nn as nn\n\nclass LSTMClassifier(nn.Module):\n    def __init__(self, vocab_size, embed_dim, hidden_dim, num_classes):\n        super().__init__()\n        pass\n    \n    def forward(self, x):\n        pass",
    solutionCode: "import torch\nimport torch.nn as nn\n\nclass LSTMClassifier(nn.Module):\n    def __init__(self, vocab_size, embed_dim, hidden_dim, num_classes):\n        super().__init__()\n        self.embedding = nn.Embedding(vocab_size, embed_dim)\n        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)\n        self.fc = nn.Linear(hidden_dim, num_classes)\n    \n    def forward(self, x):\n        embedded = self.embedding(x)\n        _, (hn, _) = self.lstm(embedded)\n        return self.fc(hn[-1])",
  },
  {
    id: "ai-hard-04",
    title: "Learning Rate Scheduler",
    difficulty: "HARD",
    points: 45,
    problemStatement: "Write a function `setup_training(model, lr, warmup_steps, total_steps)` that creates an AdamW optimizer and a linear warmup then cosine annealing scheduler. Return both.",
    sampleInput: "model, lr=3e-4, warmup_steps=1000, total_steps=10000",
    sampleOutput: "(optimizer, scheduler) tuple",
    constraints: ["Use torch.optim.AdamW.", "Use get_cosine_schedule_with_warmup from transformers or manual lambda."],
    tableSchema: { tableName: "setup_training(...)", columns: [{ name: "model", type: "nn.Module" }, { name: "Returns", type: "tuple[optimizer, scheduler]" }] },
    hints: ["Use LambdaLR with a custom lambda for warmup + cosine decay"],
    initialCode: "import torch\nimport math\n\ndef setup_training(model, lr, warmup_steps, total_steps):\n    pass",
    solutionCode: "import torch\nimport math\n\ndef setup_training(model, lr, warmup_steps, total_steps):\n    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)\n    def lr_lambda(step):\n        if step < warmup_steps:\n            return step / warmup_steps\n        progress = (step - warmup_steps) / (total_steps - warmup_steps)\n        return 0.5 * (1 + math.cos(math.pi * progress))\n    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)\n    return optimizer, scheduler",
  },
  {
    id: "ai-hard-05",
    title: "Transformer Encoder Block",
    difficulty: "HARD",
    points: 60,
    problemStatement: "Write a PyTorch nn.Module class `TransformerBlock` implementing a single Transformer encoder block: Multi-Head Self-Attention → Add & LayerNorm → Feed-Forward (Linear → ReLU → Linear) → Add & LayerNorm.",
    sampleInput: "d_model=512, num_heads=8, ff_dim=2048",
    sampleOutput: "Output tensor of shape (batch, seq_len, 512)",
    constraints: ["Use nn.MultiheadAttention.", "Apply residual connections before LayerNorm."],
    tableSchema: { tableName: "TransformerBlock", columns: [{ name: "__init__(d_model, num_heads, ff_dim)", type: "constructor" }, { name: "forward(x)", type: "torch.Tensor" }] },
    hints: ["attn_out, _ = self.mha(x, x, x); x = self.norm1(x + attn_out); ff_out = self.ff(x); x = self.norm2(x + ff_out)"],
    initialCode: "import torch\nimport torch.nn as nn\n\nclass TransformerBlock(nn.Module):\n    def __init__(self, d_model, num_heads, ff_dim):\n        super().__init__()\n        pass\n    \n    def forward(self, x):\n        pass",
    solutionCode: "import torch\nimport torch.nn as nn\n\nclass TransformerBlock(nn.Module):\n    def __init__(self, d_model, num_heads, ff_dim):\n        super().__init__()\n        self.mha = nn.MultiheadAttention(d_model, num_heads, batch_first=True)\n        self.ff = nn.Sequential(nn.Linear(d_model, ff_dim), nn.ReLU(), nn.Linear(ff_dim, d_model))\n        self.norm1 = nn.LayerNorm(d_model)\n        self.norm2 = nn.LayerNorm(d_model)\n    \n    def forward(self, x):\n        attn_out, _ = self.mha(x, x, x)\n        x = self.norm1(x + attn_out)\n        ff_out = self.ff(x)\n        x = self.norm2(x + ff_out)\n        return x",
  },
];
