export interface MLQuestion {
  id: string;
  title: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  points: number;
  problemStatement: string;
  sampleInput: string;
  sampleOutput: string;
  constraints: string[];
  tableSchema: {
    tableName: string;
    columns: { name: string; type: string }[];
  };
  hints: string[];
  initialCode: string;
  solutionCode: string;
  language?: string;
}

export const ML_QUESTION_POOL: MLQuestion[] = [
  // ==========================================
  // EASY QUESTIONS
  // ==========================================
  {
    id: "ml-easy-01",
    title: "Train-Test Split",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `split_data(X, y)` that splits features X and target y into 80% training and 20% testing sets using sklearn's train_test_split with random_state=42.",
    sampleInput: "X: array of shape (100, 5), y: array of shape (100,)",
    sampleOutput: "X_train (80, 5), X_test (20, 5), y_train (80,), y_test (20,)",
    constraints: ["Set random_state=42.", "test_size=0.2"],
    tableSchema: { tableName: "split_data(X, y)", columns: [{ name: "X", type: "np.ndarray" }, { name: "y", type: "np.ndarray" }, { name: "Returns", type: "tuple[4 arrays]" }] },
    hints: ["from sklearn.model_selection import train_test_split"],
    initialCode: "from sklearn.model_selection import train_test_split\n\ndef split_data(X, y):\n    # Split into train/test\n    pass",
    solutionCode: "from sklearn.model_selection import train_test_split\n\ndef split_data(X, y):\n    return train_test_split(X, y, test_size=0.2, random_state=42)",
  },
  {
    id: "ml-easy-02",
    title: "Standard Scaler Normalization",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `normalize_features(X_train, X_test)` that fits a StandardScaler on X_train and transforms both X_train and X_test.",
    sampleInput: "X_train and X_test numpy arrays",
    sampleOutput: "Scaled X_train and X_test with mean=0, std=1",
    constraints: ["Fit ONLY on X_train to prevent data leakage."],
    tableSchema: { tableName: "normalize_features(X_train, X_test)", columns: [{ name: "X_train", type: "np.ndarray" }, { name: "X_test", type: "np.ndarray" }, { name: "Returns", type: "tuple[2 arrays]" }] },
    hints: ["scaler.fit(X_train); X_train_scaled = scaler.transform(X_train)"],
    initialCode: "from sklearn.preprocessing import StandardScaler\n\ndef normalize_features(X_train, X_test):\n    # Fit on train, transform both\n    pass",
    solutionCode: "from sklearn.preprocessing import StandardScaler\n\ndef normalize_features(X_train, X_test):\n    scaler = StandardScaler()\n    X_train_scaled = scaler.fit_transform(X_train)\n    X_test_scaled = scaler.transform(X_test)\n    return X_train_scaled, X_test_scaled",
  },
  {
    id: "ml-easy-03",
    title: "Simple Linear Regression",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `train_linear_model(X_train, y_train)` that trains a LinearRegression model and returns it.",
    sampleInput: "X_train (80, 3), y_train (80,)",
    sampleOutput: "Fitted LinearRegression model",
    constraints: ["Use sklearn's LinearRegression."],
    tableSchema: { tableName: "train_linear_model(X_train, y_train)", columns: [{ name: "X_train", type: "np.ndarray" }, { name: "y_train", type: "np.ndarray" }, { name: "Returns", type: "LinearRegression" }] },
    hints: ["model = LinearRegression(); model.fit(X_train, y_train)"],
    initialCode: "from sklearn.linear_model import LinearRegression\n\ndef train_linear_model(X_train, y_train):\n    pass",
    solutionCode: "from sklearn.linear_model import LinearRegression\n\ndef train_linear_model(X_train, y_train):\n    model = LinearRegression()\n    model.fit(X_train, y_train)\n    return model",
  },
  {
    id: "ml-easy-04",
    title: "Accuracy Score Calculation",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `get_accuracy(y_true, y_pred)` that returns the accuracy score rounded to 4 decimal places.",
    sampleInput: "y_true = [1, 0, 1, 1], y_pred = [1, 0, 0, 1]",
    sampleOutput: "0.75",
    constraints: ["Use sklearn's accuracy_score."],
    tableSchema: { tableName: "get_accuracy(y_true, y_pred)", columns: [{ name: "y_true", type: "array" }, { name: "y_pred", type: "array" }, { name: "Returns", type: "float" }] },
    hints: ["round(accuracy_score(y_true, y_pred), 4)"],
    initialCode: "from sklearn.metrics import accuracy_score\n\ndef get_accuracy(y_true, y_pred):\n    pass",
    solutionCode: "from sklearn.metrics import accuracy_score\n\ndef get_accuracy(y_true, y_pred):\n    return round(accuracy_score(y_true, y_pred), 4)",
  },
  {
    id: "ml-easy-05",
    title: "Label Encoding Categorical Features",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `encode_labels(series)` that takes a pandas Series of categorical values and returns the label-encoded integer array using LabelEncoder.",
    sampleInput: "series = ['cat', 'dog', 'bird', 'cat']",
    sampleOutput: "[1, 2, 0, 1]",
    constraints: ["Use sklearn's LabelEncoder."],
    tableSchema: { tableName: "encode_labels(series)", columns: [{ name: "series", type: "pd.Series" }, { name: "Returns", type: "np.ndarray" }] },
    hints: ["LabelEncoder().fit_transform(series)"],
    initialCode: "from sklearn.preprocessing import LabelEncoder\n\ndef encode_labels(series):\n    pass",
    solutionCode: "from sklearn.preprocessing import LabelEncoder\n\ndef encode_labels(series):\n    le = LabelEncoder()\n    return le.fit_transform(series)",
  },
  {
    id: "ml-easy-06",
    title: "Decision Tree Classifier",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `train_decision_tree(X_train, y_train, max_depth)` that trains a DecisionTreeClassifier with the given max_depth and random_state=42.",
    sampleInput: "X_train, y_train, max_depth=5",
    sampleOutput: "Fitted DecisionTreeClassifier",
    constraints: ["Set random_state=42."],
    tableSchema: { tableName: "train_decision_tree(X_train, y_train, max_depth)", columns: [{ name: "X_train", type: "np.ndarray" }, { name: "y_train", type: "np.ndarray" }, { name: "max_depth", type: "int" }, { name: "Returns", type: "DecisionTreeClassifier" }] },
    hints: ["DecisionTreeClassifier(max_depth=max_depth, random_state=42)"],
    initialCode: "from sklearn.tree import DecisionTreeClassifier\n\ndef train_decision_tree(X_train, y_train, max_depth):\n    pass",
    solutionCode: "from sklearn.tree import DecisionTreeClassifier\n\ndef train_decision_tree(X_train, y_train, max_depth):\n    model = DecisionTreeClassifier(max_depth=max_depth, random_state=42)\n    model.fit(X_train, y_train)\n    return model",
  },
  {
    id: "ml-easy-07",
    title: "Confusion Matrix",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a function `get_confusion_matrix(y_true, y_pred)` that returns the confusion matrix as a 2D numpy array.",
    sampleInput: "y_true = [1, 0, 1, 1, 0], y_pred = [1, 0, 0, 1, 0]",
    sampleOutput: "[[2, 0], [1, 2]]",
    constraints: ["Use sklearn's confusion_matrix."],
    tableSchema: { tableName: "get_confusion_matrix(y_true, y_pred)", columns: [{ name: "y_true", type: "array" }, { name: "y_pred", type: "array" }, { name: "Returns", type: "np.ndarray" }] },
    hints: ["confusion_matrix(y_true, y_pred)"],
    initialCode: "from sklearn.metrics import confusion_matrix\n\ndef get_confusion_matrix(y_true, y_pred):\n    pass",
    solutionCode: "from sklearn.metrics import confusion_matrix\n\ndef get_confusion_matrix(y_true, y_pred):\n    return confusion_matrix(y_true, y_pred)",
  },

  // ==========================================
  // MEDIUM QUESTIONS
  // ==========================================
  {
    id: "ml-med-01",
    title: "Random Forest with Cross-Validation",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a function `rf_cross_val(X, y)` that trains a RandomForestClassifier with n_estimators=100 and evaluates it using 5-fold cross-validation. Return the mean accuracy.",
    sampleInput: "X (200, 10), y (200,)",
    sampleOutput: "Mean CV Accuracy = 0.87",
    constraints: ["Use cross_val_score with cv=5.", "random_state=42"],
    tableSchema: { tableName: "rf_cross_val(X, y)", columns: [{ name: "X", type: "np.ndarray" }, { name: "y", type: "np.ndarray" }, { name: "Returns", type: "float" }] },
    hints: ["cross_val_score(model, X, y, cv=5, scoring='accuracy').mean()"],
    initialCode: "from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import cross_val_score\n\ndef rf_cross_val(X, y):\n    pass",
    solutionCode: "from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import cross_val_score\n\ndef rf_cross_val(X, y):\n    model = RandomForestClassifier(n_estimators=100, random_state=42)\n    scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')\n    return scores.mean()",
  },
  {
    id: "ml-med-02",
    title: "Logistic Regression with ROC-AUC",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a function `logistic_roc_auc(X_train, y_train, X_test, y_test)` that trains LogisticRegression and returns the ROC-AUC score on test data.",
    sampleInput: "Train/test splits of binary classification data",
    sampleOutput: "ROC-AUC = 0.92",
    constraints: ["Use predict_proba for probability scores.", "random_state=42"],
    tableSchema: { tableName: "logistic_roc_auc(...)", columns: [{ name: "X_train, y_train", type: "np.ndarray" }, { name: "X_test, y_test", type: "np.ndarray" }, { name: "Returns", type: "float" }] },
    hints: ["roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])"],
    initialCode: "from sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import roc_auc_score\n\ndef logistic_roc_auc(X_train, y_train, X_test, y_test):\n    pass",
    solutionCode: "from sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import roc_auc_score\n\ndef logistic_roc_auc(X_train, y_train, X_test, y_test):\n    model = LogisticRegression(random_state=42, max_iter=1000)\n    model.fit(X_train, y_train)\n    probs = model.predict_proba(X_test)[:, 1]\n    return roc_auc_score(y_test, probs)",
  },
  {
    id: "ml-med-03",
    title: "K-Means Clustering",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a function `kmeans_cluster(X, n_clusters)` that fits KMeans and returns the cluster labels and inertia as a tuple.",
    sampleInput: "X (500, 4), n_clusters=3",
    sampleOutput: "(labels array, inertia float)",
    constraints: ["Set random_state=42, n_init=10."],
    tableSchema: { tableName: "kmeans_cluster(X, n_clusters)", columns: [{ name: "X", type: "np.ndarray" }, { name: "n_clusters", type: "int" }, { name: "Returns", type: "tuple[labels, inertia]" }] },
    hints: ["KMeans(n_clusters=n_clusters, random_state=42, n_init=10)"],
    initialCode: "from sklearn.cluster import KMeans\n\ndef kmeans_cluster(X, n_clusters):\n    pass",
    solutionCode: "from sklearn.cluster import KMeans\n\ndef kmeans_cluster(X, n_clusters):\n    km = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)\n    km.fit(X)\n    return km.labels_, km.inertia_",
  },
  {
    id: "ml-med-04",
    title: "Feature Importance from Random Forest",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a function `top_features(model, feature_names, n)` that returns the top-n most important features as a list of (feature_name, importance) tuples sorted descending.",
    sampleInput: "Fitted RandomForest, feature names list, n=5",
    sampleOutput: "[('age', 0.35), ('income', 0.22), ...]",
    constraints: ["Sort by importance descending."],
    tableSchema: { tableName: "top_features(model, feature_names, n)", columns: [{ name: "model", type: "fitted sklearn model" }, { name: "feature_names", type: "list[str]" }, { name: "Returns", type: "list[tuple]" }] },
    hints: ["zip(feature_names, model.feature_importances_), sort by [1] desc"],
    initialCode: "def top_features(model, feature_names, n):\n    pass",
    solutionCode: "def top_features(model, feature_names, n):\n    pairs = list(zip(feature_names, model.feature_importances_))\n    pairs.sort(key=lambda x: x[1], reverse=True)\n    return pairs[:n]",
  },
  {
    id: "ml-med-05",
    title: "PCA Dimensionality Reduction",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a function `apply_pca(X, n_components)` that applies PCA to reduce dimensionality and returns the transformed array and the explained variance ratio.",
    sampleInput: "X (200, 20), n_components=5",
    sampleOutput: "(X_pca (200, 5), explained_variance_ratio array)",
    constraints: ["Use sklearn's PCA.", "random_state=42"],
    tableSchema: { tableName: "apply_pca(X, n_components)", columns: [{ name: "X", type: "np.ndarray" }, { name: "n_components", type: "int" }, { name: "Returns", type: "tuple" }] },
    hints: ["pca = PCA(n_components=n_components, random_state=42)"],
    initialCode: "from sklearn.decomposition import PCA\n\ndef apply_pca(X, n_components):\n    pass",
    solutionCode: "from sklearn.decomposition import PCA\n\ndef apply_pca(X, n_components):\n    pca = PCA(n_components=n_components, random_state=42)\n    X_pca = pca.fit_transform(X)\n    return X_pca, pca.explained_variance_ratio_",
  },
  {
    id: "ml-med-06",
    title: "Precision, Recall, F1 Report",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a function `classification_report_dict(y_true, y_pred)` that returns sklearn's classification_report as a dictionary.",
    sampleInput: "y_true and y_pred arrays",
    sampleOutput: "Dictionary with precision, recall, f1-score per class",
    constraints: ["Use output_dict=True parameter."],
    tableSchema: { tableName: "classification_report_dict(y_true, y_pred)", columns: [{ name: "y_true", type: "array" }, { name: "y_pred", type: "array" }, { name: "Returns", type: "dict" }] },
    hints: ["classification_report(y_true, y_pred, output_dict=True)"],
    initialCode: "from sklearn.metrics import classification_report\n\ndef classification_report_dict(y_true, y_pred):\n    pass",
    solutionCode: "from sklearn.metrics import classification_report\n\ndef classification_report_dict(y_true, y_pred):\n    return classification_report(y_true, y_pred, output_dict=True)",
  },
  {
    id: "ml-med-07",
    title: "Sklearn Pipeline with Scaler + SVM",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a function `build_svm_pipeline()` that creates a sklearn Pipeline with StandardScaler followed by SVC with kernel='rbf' and random_state=42.",
    sampleInput: "No input (returns pipeline object)",
    sampleOutput: "Pipeline(steps=[('scaler', StandardScaler()), ('svm', SVC(...))])",
    constraints: ["Use Pipeline from sklearn."],
    tableSchema: { tableName: "build_svm_pipeline()", columns: [{ name: "Returns", type: "Pipeline" }] },
    hints: ["Pipeline([('scaler', StandardScaler()), ('svm', SVC(kernel='rbf', random_state=42))])"],
    initialCode: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.svm import SVC\n\ndef build_svm_pipeline():\n    pass",
    solutionCode: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.svm import SVC\n\ndef build_svm_pipeline():\n    return Pipeline([('scaler', StandardScaler()), ('svm', SVC(kernel='rbf', random_state=42))])",
  },

  // ==========================================
  // HARD QUESTIONS
  // ==========================================
  {
    id: "ml-hard-01",
    title: "XGBoost with GridSearchCV",
    difficulty: "HARD",
    points: 45,
    problemStatement: "Write a function `xgb_grid_search(X_train, y_train)` that performs GridSearchCV on XGBClassifier with param_grid: n_estimators=[50, 100, 200], max_depth=[3, 5, 7], learning_rate=[0.01, 0.1]. Return the best estimator.",
    sampleInput: "X_train (500, 15), y_train (500,)",
    sampleOutput: "Best XGBClassifier with optimal hyperparameters",
    constraints: ["cv=3, scoring='accuracy', random_state=42"],
    tableSchema: { tableName: "xgb_grid_search(X_train, y_train)", columns: [{ name: "X_train", type: "np.ndarray" }, { name: "y_train", type: "np.ndarray" }, { name: "Returns", type: "XGBClassifier" }] },
    hints: ["GridSearchCV(XGBClassifier(random_state=42), param_grid, cv=3)"],
    initialCode: "from xgboost import XGBClassifier\nfrom sklearn.model_selection import GridSearchCV\n\ndef xgb_grid_search(X_train, y_train):\n    pass",
    solutionCode: "from xgboost import XGBClassifier\nfrom sklearn.model_selection import GridSearchCV\n\ndef xgb_grid_search(X_train, y_train):\n    param_grid = {'n_estimators': [50, 100, 200], 'max_depth': [3, 5, 7], 'learning_rate': [0.01, 0.1]}\n    grid = GridSearchCV(XGBClassifier(random_state=42), param_grid, cv=3, scoring='accuracy')\n    grid.fit(X_train, y_train)\n    return grid.best_estimator_",
  },
  {
    id: "ml-hard-02",
    title: "SMOTE for Imbalanced Data",
    difficulty: "HARD",
    points: 45,
    problemStatement: "Write a function `balance_with_smote(X_train, y_train)` that applies SMOTE oversampling to balance a binary classification dataset. Return the resampled X and y.",
    sampleInput: "Imbalanced X_train (1000, 10), y_train with 90% class 0",
    sampleOutput: "Balanced X_resampled and y_resampled (50/50 split)",
    constraints: ["Use imblearn's SMOTE with random_state=42."],
    tableSchema: { tableName: "balance_with_smote(X_train, y_train)", columns: [{ name: "X_train", type: "np.ndarray" }, { name: "y_train", type: "np.ndarray" }, { name: "Returns", type: "tuple[X_res, y_res]" }] },
    hints: ["SMOTE(random_state=42).fit_resample(X_train, y_train)"],
    initialCode: "from imblearn.over_sampling import SMOTE\n\ndef balance_with_smote(X_train, y_train):\n    pass",
    solutionCode: "from imblearn.over_sampling import SMOTE\n\ndef balance_with_smote(X_train, y_train):\n    smote = SMOTE(random_state=42)\n    return smote.fit_resample(X_train, y_train)",
  },
  {
    id: "ml-hard-03",
    title: "Custom Sklearn Transformer",
    difficulty: "HARD",
    points: 50,
    problemStatement: "Write a custom sklearn transformer class `LogTransformer` that applies np.log1p in fit_transform and np.expm1 in inverse_transform. It should inherit from BaseEstimator and TransformerMixin.",
    sampleInput: "X array with positive values",
    sampleOutput: "Log-transformed X values",
    constraints: ["Must implement fit, transform, and inverse_transform.", "Must inherit BaseEstimator, TransformerMixin."],
    tableSchema: { tableName: "LogTransformer", columns: [{ name: "fit(X)", type: "self" }, { name: "transform(X)", type: "np.ndarray" }, { name: "inverse_transform(X)", type: "np.ndarray" }] },
    hints: ["np.log1p(X) for transform, np.expm1(X) for inverse"],
    initialCode: "import numpy as np\nfrom sklearn.base import BaseEstimator, TransformerMixin\n\nclass LogTransformer(BaseEstimator, TransformerMixin):\n    pass",
    solutionCode: "import numpy as np\nfrom sklearn.base import BaseEstimator, TransformerMixin\n\nclass LogTransformer(BaseEstimator, TransformerMixin):\n    def fit(self, X, y=None):\n        return self\n    def transform(self, X):\n        return np.log1p(X)\n    def inverse_transform(self, X):\n        return np.expm1(X)",
  },
  {
    id: "ml-hard-04",
    title: "Elbow Method for Optimal K",
    difficulty: "HARD",
    points: 45,
    problemStatement: "Write a function `find_optimal_k(X, k_range)` that computes inertia for each k in k_range using KMeans and returns a list of (k, inertia) tuples.",
    sampleInput: "X (300, 5), k_range=range(2, 11)",
    sampleOutput: "[(2, 850.3), (3, 420.1), ..., (10, 95.2)]",
    constraints: ["random_state=42 for each KMeans.", "n_init=10"],
    tableSchema: { tableName: "find_optimal_k(X, k_range)", columns: [{ name: "X", type: "np.ndarray" }, { name: "k_range", type: "range" }, { name: "Returns", type: "list[tuple]" }] },
    hints: ["Loop over k_range, fit KMeans, append (k, km.inertia_)"],
    initialCode: "from sklearn.cluster import KMeans\n\ndef find_optimal_k(X, k_range):\n    pass",
    solutionCode: "from sklearn.cluster import KMeans\n\ndef find_optimal_k(X, k_range):\n    results = []\n    for k in k_range:\n        km = KMeans(n_clusters=k, random_state=42, n_init=10)\n        km.fit(X)\n        results.append((k, km.inertia_))\n    return results",
  },
  {
    id: "ml-hard-05",
    title: "Stacking Ensemble Classifier",
    difficulty: "HARD",
    points: 50,
    problemStatement: "Write a function `build_stacking_classifier()` that creates a StackingClassifier with base estimators: LogisticRegression, RandomForestClassifier, SVC (with probability=True), and a final estimator of LogisticRegression.",
    sampleInput: "No input",
    sampleOutput: "StackingClassifier with 3 base + 1 meta estimator",
    constraints: ["All estimators: random_state=42."],
    tableSchema: { tableName: "build_stacking_classifier()", columns: [{ name: "Returns", type: "StackingClassifier" }] },
    hints: ["StackingClassifier(estimators=[...], final_estimator=LogisticRegression())"],
    initialCode: "from sklearn.ensemble import StackingClassifier, RandomForestClassifier\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.svm import SVC\n\ndef build_stacking_classifier():\n    pass",
    solutionCode: "from sklearn.ensemble import StackingClassifier, RandomForestClassifier\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.svm import SVC\n\ndef build_stacking_classifier():\n    estimators = [\n        ('lr', LogisticRegression(random_state=42, max_iter=1000)),\n        ('rf', RandomForestClassifier(random_state=42)),\n        ('svc', SVC(probability=True, random_state=42)),\n    ]\n    return StackingClassifier(estimators=estimators, final_estimator=LogisticRegression(random_state=42))",
  },
];
