export interface PowerBIQuestion {
  id: string;
  title: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  points: number;
  problemStatement: string;
  sampleInput: string;
  sampleOutput: string;
  constraints: string[];
  tableSchema: {
    tableName: string;
    columns: { name: string; type: string }[];
  };
  hints: string[];
  initialCode: string;
  solutionCode: string;
  language?: string;
}

export const POWERBI_QUESTION_POOL: PowerBIQuestion[] = [
  // ==========================================
  // EASY QUESTIONS (15+)
  // ==========================================
  {
    id: "pbi-easy-01",
    title: "Total Sales Measure",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a DAX measure `Total Sales` that calculates the sum of the `Amount` column from the `Sales` table.",
    sampleInput: "Sales table with Amount column",
    sampleOutput: "Total Sales = 125,000",
    constraints: ["Use the SUM function."],
    tableSchema: { tableName: "Sales", columns: [{ name: "OrderID", type: "INT" }, { name: "Amount", type: "DECIMAL" }, { name: "Date", type: "DATE" }] },
    hints: ["SUM(Sales[Amount])"],
    initialCode: "Total Sales = \n// Write your DAX measure here",
    solutionCode: "Total Sales = SUM(Sales[Amount])",
  },
  {
    id: "pbi-easy-02",
    title: "Count of Customers",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a DAX measure `Customer Count` that counts the distinct number of customers from the `Orders` table.",
    sampleInput: "Orders table with CustomerID column",
    sampleOutput: "Customer Count = 342",
    constraints: ["Use DISTINCTCOUNT function."],
    tableSchema: { tableName: "Orders", columns: [{ name: "OrderID", type: "INT" }, { name: "CustomerID", type: "INT" }, { name: "Amount", type: "DECIMAL" }] },
    hints: ["DISTINCTCOUNT(Orders[CustomerID])"],
    initialCode: "Customer Count = \n// Write your DAX measure here",
    solutionCode: "Customer Count = DISTINCTCOUNT(Orders[CustomerID])",
  },
  {
    id: "pbi-easy-03",
    title: "Average Order Value",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a DAX measure `Avg Order Value` that computes the average of the `Amount` column from the `Orders` table.",
    sampleInput: "Orders table with Amount column",
    sampleOutput: "Avg Order Value = 365.50",
    constraints: ["Use AVERAGE function."],
    tableSchema: { tableName: "Orders", columns: [{ name: "OrderID", type: "INT" }, { name: "Amount", type: "DECIMAL" }] },
    hints: ["AVERAGE(Orders[Amount])"],
    initialCode: "Avg Order Value = \n// Write your DAX measure here",
    solutionCode: "Avg Order Value = AVERAGE(Orders[Amount])",
  },
  {
    id: "pbi-easy-04",
    title: "Max Sale Amount",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a DAX measure `Max Sale` that returns the maximum value of the `SaleAmount` column from the `Transactions` table.",
    sampleInput: "Transactions table with SaleAmount column",
    sampleOutput: "Max Sale = 9,999.99",
    constraints: ["Use MAX function."],
    tableSchema: { tableName: "Transactions", columns: [{ name: "TxnID", type: "INT" }, { name: "SaleAmount", type: "DECIMAL" }] },
    hints: ["MAX(Transactions[SaleAmount])"],
    initialCode: "Max Sale = \n// Write your DAX measure here",
    solutionCode: "Max Sale = MAX(Transactions[SaleAmount])",
  },
  {
    id: "pbi-easy-05",
    title: "Profit Margin Calculated Column",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a DAX calculated column `Profit Margin` in the `Products` table that divides `Profit` by `Revenue`.",
    sampleInput: "Products table with Revenue and Profit columns",
    sampleOutput: "Profit Margin = 0.35",
    constraints: ["Handle division by zero with DIVIDE function."],
    tableSchema: { tableName: "Products", columns: [{ name: "ProductID", type: "INT" }, { name: "Revenue", type: "DECIMAL" }, { name: "Profit", type: "DECIMAL" }] },
    hints: ["DIVIDE(Products[Profit], Products[Revenue], 0)"],
    initialCode: "Profit Margin = \n// Write your DAX calculated column here",
    solutionCode: "Profit Margin = DIVIDE(Products[Profit], Products[Revenue], 0)",
  },
  {
    id: "pbi-easy-06",
    title: "Row Count Measure",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a DAX measure `Total Rows` that counts the total number of rows in the `FactSales` table.",
    sampleInput: "FactSales table",
    sampleOutput: "Total Rows = 10,543",
    constraints: ["Use COUNTROWS function."],
    tableSchema: { tableName: "FactSales", columns: [{ name: "SaleID", type: "INT" }, { name: "Amount", type: "DECIMAL" }] },
    hints: ["COUNTROWS(FactSales)"],
    initialCode: "Total Rows = \n// Write your DAX measure here",
    solutionCode: "Total Rows = COUNTROWS(FactSales)",
  },
  {
    id: "pbi-easy-07",
    title: "Concatenated Full Name Column",
    difficulty: "EASY",
    points: 15,
    problemStatement: "Write a DAX calculated column `Full Name` in the `Employees` table that concatenates `FirstName` and `LastName` with a space.",
    sampleInput: "Employees table with FirstName, LastName",
    sampleOutput: "Full Name = 'John Smith'",
    constraints: ["Use the & operator or CONCATENATE function."],
    tableSchema: { tableName: "Employees", columns: [{ name: "EmpID", type: "INT" }, { name: "FirstName", type: "TEXT" }, { name: "LastName", type: "TEXT" }] },
    hints: ["Employees[FirstName] & \" \" & Employees[LastName]"],
    initialCode: "Full Name = \n// Write your DAX calculated column here",
    solutionCode: "Full Name = Employees[FirstName] & \" \" & Employees[LastName]",
  },

  // ==========================================
  // MEDIUM QUESTIONS (15+)
  // ==========================================
  {
    id: "pbi-med-01",
    title: "Year-to-Date Sales (TOTALYTD)",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a DAX measure `YTD Sales` that calculates year-to-date sales using the TOTALYTD function over the `Sales[Amount]` column and the `Calendar[Date]` column.",
    sampleInput: "Sales and Calendar tables",
    sampleOutput: "YTD Sales = 1,250,000",
    constraints: ["Use TOTALYTD with the Calendar date column."],
    tableSchema: { tableName: "Sales", columns: [{ name: "Amount", type: "DECIMAL" }, { name: "DateKey", type: "INT" }] },
    hints: ["TOTALYTD(SUM(Sales[Amount]), Calendar[Date])"],
    initialCode: "YTD Sales = \n// Write your DAX measure using TOTALYTD",
    solutionCode: "YTD Sales = TOTALYTD(SUM(Sales[Amount]), Calendar[Date])",
  },
  {
    id: "pbi-med-02",
    title: "Previous Month Sales (CALCULATE + DATEADD)",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a DAX measure `Prev Month Sales` that returns the total sales from the previous month using CALCULATE and DATEADD.",
    sampleInput: "Sales and Calendar tables",
    sampleOutput: "Prev Month Sales = 98,500",
    constraints: ["Use CALCULATE with DATEADD shifting -1 month."],
    tableSchema: { tableName: "Sales", columns: [{ name: "Amount", type: "DECIMAL" }] },
    hints: ["CALCULATE(SUM(Sales[Amount]), DATEADD(Calendar[Date], -1, MONTH))"],
    initialCode: "Prev Month Sales = \n// Use CALCULATE + DATEADD",
    solutionCode: "Prev Month Sales = CALCULATE(SUM(Sales[Amount]), DATEADD(Calendar[Date], -1, MONTH))",
  },
  {
    id: "pbi-med-03",
    title: "Sales for Specific Category (CALCULATE + FILTER)",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a DAX measure `Electronics Sales` that calculates total sales filtered to only the 'Electronics' category using CALCULATE.",
    sampleInput: "Sales table joined to Products with Category column",
    sampleOutput: "Electronics Sales = 450,000",
    constraints: ["Use CALCULATE with a filter on Product[Category]."],
    tableSchema: { tableName: "Sales", columns: [{ name: "Amount", type: "DECIMAL" }, { name: "ProductKey", type: "INT" }] },
    hints: ["CALCULATE(SUM(Sales[Amount]), Products[Category] = \"Electronics\")"],
    initialCode: "Electronics Sales = \n// Write CALCULATE with filter context",
    solutionCode: "Electronics Sales = CALCULATE(SUM(Sales[Amount]), Products[Category] = \"Electronics\")",
  },
  {
    id: "pbi-med-04",
    title: "Running Total with CALCULATE + FILTER",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a DAX measure `Running Total` that computes a cumulative running total of sales amount ordered by date.",
    sampleInput: "Sales and Calendar tables",
    sampleOutput: "Running Total accumulates across months",
    constraints: ["Use CALCULATE with FILTER(ALL(...))."],
    tableSchema: { tableName: "Sales", columns: [{ name: "Amount", type: "DECIMAL" }] },
    hints: ["CALCULATE(SUM(Sales[Amount]), FILTER(ALL(Calendar[Date]), Calendar[Date] <= MAX(Calendar[Date])))"],
    initialCode: "Running Total = \n// Implement running total with CALCULATE",
    solutionCode: "Running Total = CALCULATE(SUM(Sales[Amount]), FILTER(ALL(Calendar[Date]), Calendar[Date] <= MAX(Calendar[Date])))",
  },
  {
    id: "pbi-med-05",
    title: "Percentage of Total (DIVIDE + ALL)",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a DAX measure `% of Total Sales` that shows each category's sales as a percentage of total overall sales.",
    sampleInput: "Sales table with category context",
    sampleOutput: "% of Total Sales = 23.5%",
    constraints: ["Use DIVIDE with CALCULATE + ALL to get grand total."],
    tableSchema: { tableName: "Sales", columns: [{ name: "Amount", type: "DECIMAL" }] },
    hints: ["DIVIDE(SUM(Sales[Amount]), CALCULATE(SUM(Sales[Amount]), ALL(Sales)))"],
    initialCode: "% of Total Sales = \n// Compute percentage using ALL",
    solutionCode: "% of Total Sales = DIVIDE(SUM(Sales[Amount]), CALCULATE(SUM(Sales[Amount]), ALL(Sales)))",
  },
  {
    id: "pbi-med-06",
    title: "RANKX Product Ranking",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a DAX measure `Product Rank` that ranks products by their total sales in descending order using RANKX.",
    sampleInput: "Products and Sales tables",
    sampleOutput: "Product Rank = 1 (for top seller)",
    constraints: ["Use RANKX with ALL(Products)."],
    tableSchema: { tableName: "Products", columns: [{ name: "ProductName", type: "TEXT" }, { name: "ProductKey", type: "INT" }] },
    hints: ["RANKX(ALL(Products), SUM(Sales[Amount]),,DESC)"],
    initialCode: "Product Rank = \n// Use RANKX to rank products",
    solutionCode: "Product Rank = RANKX(ALL(Products), SUM(Sales[Amount]),,DESC)",
  },
  {
    id: "pbi-med-07",
    title: "SUMX Row-Level Calculation",
    difficulty: "MEDIUM",
    points: 30,
    problemStatement: "Write a DAX measure `Total Revenue` that iterates over each row in the `Sales` table and multiplies `Quantity` by `UnitPrice`, then sums the results using SUMX.",
    sampleInput: "Sales table with Quantity and UnitPrice columns",
    sampleOutput: "Total Revenue = 875,000",
    constraints: ["Must use SUMX for row-level calculation."],
    tableSchema: { tableName: "Sales", columns: [{ name: "Quantity", type: "INT" }, { name: "UnitPrice", type: "DECIMAL" }] },
    hints: ["SUMX(Sales, Sales[Quantity] * Sales[UnitPrice])"],
    initialCode: "Total Revenue = \n// Use SUMX for row-level calculation",
    solutionCode: "Total Revenue = SUMX(Sales, Sales[Quantity] * Sales[UnitPrice])",
  },

  // ==========================================
  // HARD QUESTIONS (10+)
  // ==========================================
  {
    id: "pbi-hard-01",
    title: "Month-over-Month Growth %",
    difficulty: "HARD",
    points: 45,
    problemStatement: "Write a DAX measure `MoM Growth %` that computes the month-over-month percentage growth in sales. Show the result as a percentage.",
    sampleInput: "Sales and Calendar tables",
    sampleOutput: "MoM Growth % = 12.5%",
    constraints: ["Handle first month (no prior) gracefully with BLANK()."],
    tableSchema: { tableName: "Sales", columns: [{ name: "Amount", type: "DECIMAL" }] },
    hints: ["VAR CurrentMonth = SUM(Sales[Amount]); VAR PrevMonth = CALCULATE(..., DATEADD(..., -1, MONTH)); DIVIDE(CurrentMonth - PrevMonth, PrevMonth)"],
    initialCode: "MoM Growth % = \n// Compute month-over-month growth",
    solutionCode: "MoM Growth % = \nVAR CurrentMonth = SUM(Sales[Amount])\nVAR PrevMonth = CALCULATE(SUM(Sales[Amount]), DATEADD(Calendar[Date], -1, MONTH))\nRETURN DIVIDE(CurrentMonth - PrevMonth, PrevMonth, BLANK())",
  },
  {
    id: "pbi-hard-02",
    title: "Dynamic Top N with TOPN + CALCULATE",
    difficulty: "HARD",
    points: 45,
    problemStatement: "Write a DAX measure `Top 5 Product Sales` that calculates sales only for the top 5 products by revenue using CALCULATE, TOPN, and SUMX.",
    sampleInput: "Sales and Products tables",
    sampleOutput: "Top 5 Product Sales = 650,000",
    constraints: ["Use TOPN inside CALCULATE with a summary table."],
    tableSchema: { tableName: "Sales", columns: [{ name: "Amount", type: "DECIMAL" }, { name: "ProductKey", type: "INT" }] },
    hints: ["CALCULATE(SUM(Sales[Amount]), TOPN(5, ALL(Products), SUM(Sales[Amount]), DESC))"],
    initialCode: "Top 5 Product Sales = \n// Implement TOPN filtering",
    solutionCode: "Top 5 Product Sales = CALCULATE(SUM(Sales[Amount]), TOPN(5, ALL(Products), SUM(Sales[Amount]), DESC))",
  },
  {
    id: "pbi-hard-03",
    title: "Semi-Additive Balance (LASTNONBLANK)",
    difficulty: "HARD",
    points: 45,
    problemStatement: "Write a DAX measure `Ending Balance` that returns the last non-blank balance for each account using LASTNONBLANK.",
    sampleInput: "FactBalance table with AccountID, Date, Balance",
    sampleOutput: "Ending Balance = 125,000 (last known balance)",
    constraints: ["Use CALCULATE with LASTNONBLANK for semi-additive logic."],
    tableSchema: { tableName: "FactBalance", columns: [{ name: "AccountID", type: "INT" }, { name: "Date", type: "DATE" }, { name: "Balance", type: "DECIMAL" }] },
    hints: ["CALCULATE(SUM(FactBalance[Balance]), LASTNONBLANK(Calendar[Date], SUM(FactBalance[Balance])))"],
    initialCode: "Ending Balance = \n// Use LASTNONBLANK for semi-additive",
    solutionCode: "Ending Balance = CALCULATE(SUM(FactBalance[Balance]), LASTNONBLANK(Calendar[Date], SUM(FactBalance[Balance])))",
  },
  {
    id: "pbi-hard-04",
    title: "Year-over-Year Comparison (SAMEPERIODLASTYEAR)",
    difficulty: "HARD",
    points: 45,
    problemStatement: "Write a DAX measure `YoY Growth %` that computes year-over-year sales growth using SAMEPERIODLASTYEAR.",
    sampleInput: "Sales and Calendar tables",
    sampleOutput: "YoY Growth % = 18.3%",
    constraints: ["Use SAMEPERIODLASTYEAR for the prior year context."],
    tableSchema: { tableName: "Sales", columns: [{ name: "Amount", type: "DECIMAL" }] },
    hints: ["VAR LY = CALCULATE(SUM(Sales[Amount]), SAMEPERIODLASTYEAR(Calendar[Date]))"],
    initialCode: "YoY Growth % = \n// Compute year-over-year growth",
    solutionCode: "YoY Growth % = \nVAR CY = SUM(Sales[Amount])\nVAR LY = CALCULATE(SUM(Sales[Amount]), SAMEPERIODLASTYEAR(Calendar[Date]))\nRETURN DIVIDE(CY - LY, LY, BLANK())",
  },
  {
    id: "pbi-hard-05",
    title: "Dynamic ABC Classification",
    difficulty: "HARD",
    points: 50,
    problemStatement: "Write a DAX calculated column `ABC Class` that classifies products: A (top 80% of revenue), B (next 15%), C (bottom 5%) using RANKX and cumulative percentages.",
    sampleInput: "Products table with aggregated revenue",
    sampleOutput: "ABC Class = 'A' for top contributors",
    constraints: ["Must use RANKX, SUMX, and SWITCH for classification."],
    tableSchema: { tableName: "Products", columns: [{ name: "ProductKey", type: "INT" }, { name: "TotalRevenue", type: "DECIMAL" }] },
    hints: ["Compute cumulative % then use SWITCH(TRUE(), CumPct <= 0.8, \"A\", CumPct <= 0.95, \"B\", \"C\")"],
    initialCode: "ABC Class = \n// Implement ABC classification with RANKX",
    solutionCode: "ABC Class = \nVAR TotalRev = SUMX(ALL(Products), Products[TotalRevenue])\nVAR CumRev = SUMX(FILTER(ALL(Products), RANKX(ALL(Products), Products[TotalRevenue],,DESC) <= RANKX(ALL(Products), Products[TotalRevenue],,DESC)), Products[TotalRevenue])\nVAR CumPct = DIVIDE(CumRev, TotalRev)\nRETURN SWITCH(TRUE(), CumPct <= 0.8, \"A\", CumPct <= 0.95, \"B\", \"C\")",
  },
];
